# Generated by Django 6.0 on 2025-12-30 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('lon', models.FloatField(blank=True, db_column='long', null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherForecastHourly',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('forecast_time', models.DateTimeField()),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('wind_dir_deg', models.FloatField(blank=True, null=True)),
                ('cloud_cover_percent', models.FloatField(blank=True, null=True)),
                ('precip_mm', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_forecast_hourly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.TextField(unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('forecast_days', models.IntegerField(default=10)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'forecast_cache',
            },
        ),
    ]
